CREATE TABLE STATION (
    ID INT,
    CITY VARCHAR(21),
    STATE VARCHAR(2),
    LAT_N FLOAT,
    LONG_W FLOAT
);

INSERT INTO STATION VALUES (1, 'CityA', 'CA', 20.5, 50.1);
INSERT INTO STATION VALUES (2, 'CityB', 'TX', 10.0, 40.0);
INSERT INTO STATION VALUES (3, 'CityC', 'NY', 35.6, 60.3);
INSERT INTO STATION VALUES (4, 'CityD', 'WA', 50.0, 30.0);

SELECT ROUND(
    ABS(MAX(LAT_N) - MIN(LAT_N)) + ABS(MAX(LONG_W) - MIN(LONG_W)), 4
)
FROM STATION;
